import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — ragornot",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14">
      <h1 className="mb-8 text-3xl font-bold tracking-tight text-text">Terms of Use</h1>
      <div className="flex flex-col gap-6 text-sm text-text-muted [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-text [&_h2]:mt-2">

        <section>
          <h2>Independent project</h2>
          <p className="mt-2">
            ragornot is an independent research and demonstration project. It is not affiliated with,
            endorsed by, or sponsored by Amazon Web Services or Amazon.com, Inc. AWS and related marks
            are trademarks of Amazon.com, Inc.
          </p>
        </section>

        <section>
          <h2>Acceptable use</h2>
          <p className="mt-2">
            You may use ragornot for personal learning, research, and evaluation of retrieval
            architectures. You may not:
          </p>
          <ul className="mt-2 list-disc pl-5 flex flex-col gap-1">
            <li>Automate or script requests in volume (the rate limits exist to protect a shared resource).</li>
            <li>Attempt to circumvent rate limits, quotas, or the origin-verify protection.</li>
            <li>Use the LLM/RAG Explore modes as a general-purpose AI chatbot or proxy.</li>
            <li>Use the service in any way that violates applicable law.</li>
          </ul>
        </section>

        <section>
          <h2>AI-generated content</h2>
          <p className="mt-2">
            Answers generated by LLM-only and RAG modes are produced by Amazon Bedrock (Claude) and
            may be inaccurate, incomplete, or outdated. They are provided for educational comparison
            only. Always verify information against{" "}
            <a
              href="https://docs.aws.amazon.com"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-accent-text"
            >
              official AWS documentation
            </a>{" "}
            before acting on it.
          </p>
        </section>

        <section>
          <h2>News aggregation</h2>
          <p className="mt-2">
            The News tab aggregates headlines and short excerpts from public RSS feeds and links to
            the original publisher. ragornot does not reproduce full article text and does not claim
            ownership of any third-party content. If you are a publisher and have concerns about how
            your content appears, contact us.
          </p>
        </section>

        <section>
          <h2>No warranty</h2>
          <p className="mt-2">
            ragornot is provided &quot;as is&quot; with no warranty of any kind. Uptime, accuracy, and
            availability of the live backend are not guaranteed.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p className="mt-2">
            These terms may be updated at any time. Continued use of the site constitutes acceptance
            of the current terms.
          </p>
        </section>

        <p className="text-xs mt-4">Last updated: July 2026</p>
      </div>
    </div>
  );
}
